<?php

namespace ContainerVMSiJA7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F2KPINPService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.service_locator.f2KPINP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f2KPINP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clienteRepository' => ['privates', 'App\\Repository\\ClienteRepository', 'getClienteRepositoryService', true],
            'orderItemRepository' => ['privates', 'App\\Repository\\OrderItemRepository', 'getOrderItemRepositoryService', true],
            'pedido' => ['privates', '.errored..service_locator.f2KPINP.App\\Entity\\Pedido', NULL, 'Cannot autowire service ".service_locator.f2KPINP": it references class "App\\Entity\\Pedido" but no such service exists.'],
        ], [
            'clienteRepository' => 'App\\Repository\\ClienteRepository',
            'orderItemRepository' => 'App\\Repository\\OrderItemRepository',
            'pedido' => 'App\\Entity\\Pedido',
        ]);
    }
}
