<?php

namespace ContainerVMSiJA7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JmVMimgService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.service_locator.jmVMimg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jmVMimg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'order' => ['privates', '.errored..service_locator.jmVMimg.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.jmVMimg": it references class "App\\Entity\\Order" but no such service exists.'],
        ], [
            'order' => 'App\\Entity\\Order',
        ]);
    }
}
