<?php

namespace ContainerVMSiJA7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MJheJViService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.service_locator.mJheJVi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mJheJVi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'orderItem' => ['privates', '.errored..service_locator.mJheJVi.App\\Entity\\OrderItem', NULL, 'Cannot autowire service ".service_locator.mJheJVi": it references class "App\\Entity\\OrderItem" but no such service exists.'],
        ], [
            'orderItem' => 'App\\Entity\\OrderItem',
        ]);
    }
}
