<?php

namespace ContainerVMSiJA7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cv0zgLlService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.service_locator.cv0zgLl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cv0zgLl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'novedade' => ['privates', '.errored..service_locator.cv0zgLl.App\\Entity\\Novedades', NULL, 'Cannot autowire service ".service_locator.cv0zgLl": it references class "App\\Entity\\Novedades" but no such service exists.'],
        ], [
            'novedade' => 'App\\Entity\\Novedades',
        ]);
    }
}
