<?php

namespace ContainerVMSiJA7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7Q5fXtm.App\Entity\OrderItem' shared service.
     *
     * @return \App\Entity\OrderItem
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7Q5fXtm": it references class "App\\Entity\\OrderItem" but no such service exists.');
    }
}
