<?php

namespace ContainerVMSiJA7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedido2TypeService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private 'App\Form\Pedido2Type' shared autowired service.
     *
     * @return \App\Form\Pedido2Type
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Pedido2Type.php';

        return $container->privates['App\\Form\\Pedido2Type'] = new \App\Form\Pedido2Type();
    }
}
