<?php

namespace ContainerVMSiJA7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStock2Service extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QWF29IA.App\Entity\Stock' shared service.
     *
     * @return \App\Entity\Stock
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QWF29IA": it references class "App\\Entity\\Stock" but no such service exists.');
    }
}
