<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KCWh3QqService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.service_locator.KCWh3Qq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KCWh3Qq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'role' => ['privates', '.errored..service_locator.KCWh3Qq.App\\Entity\\Role', NULL, 'Cannot autowire service ".service_locator.KCWh3Qq": it references class "App\\Entity\\Role" but no such service exists.'],
        ], [
            'role' => 'App\\Entity\\Role',
        ]);
    }
}
