<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3BGMwHService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.service_locator.3B_gMwH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3B_gMwH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'stock' => ['privates', '.errored..service_locator.3B_gMwH.App\\Entity\\Stock', NULL, 'Cannot autowire service ".service_locator.3B_gMwH": it references class "App\\Entity\\Stock" but no such service exists.'],
        ], [
            'stock' => 'App\\Entity\\Stock',
        ]);
    }
}
