<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XjuMoQHService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.service_locator.XjuMoQH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XjuMoQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'orderItemRepository' => ['privates', 'App\\Repository\\OrderItemRepository', 'getOrderItemRepositoryService', true],
        ], [
            'orderItemRepository' => 'App\\Repository\\OrderItemRepository',
        ]);
    }
}
