<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClienteService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FWfeBs9.App\Entity\Cliente' shared service.
     *
     * @return \App\Entity\Cliente
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.FWfeBs9": it references class "App\\Entity\\Cliente" but no such service exists.');
    }
}
