<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriaService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QuHKGW_.App\Entity\Categoria' shared service.
     *
     * @return \App\Entity\Categoria
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QuHKGW_": it references class "App\\Entity\\Categoria" but no such service exists.');
    }
}
