<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNovedadesService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bEG_bB2.App\Entity\Novedades' shared service.
     *
     * @return \App\Entity\Novedades
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bEG_bB2": it references class "App\\Entity\\Novedades" but no such service exists.');
    }
}
