<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrder2Service extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jmVMimg.App\Entity\Order' shared service.
     *
     * @return \App\Entity\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jmVMimg": it references class "App\\Entity\\Order" but no such service exists.');
    }
}
