<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProducto4Service extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._i2YZ1n.App\Entity\Producto' shared service.
     *
     * @return \App\Entity\Producto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._i2YZ1n": it references class "App\\Entity\\Producto" but no such service exists.');
    }
}
