<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KCWh3Qq.App\Entity\Role' shared service.
     *
     * @return \App\Entity\Role
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KCWh3Qq": it references class "App\\Entity\\Role" but no such service exists.');
    }
}
