<?php

namespace ContainerVZ97f0k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockService extends App_KernelDewDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3B_gMwH.App\Entity\Stock' shared service.
     *
     * @return \App\Entity\Stock
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.3B_gMwH": it references class "App\\Entity\\Stock" but no such service exists.');
    }
}
