<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHBGT31Q\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHBGT31Q/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHBGT31Q.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHBGT31Q\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHBGT31Q\App_KernelProdContainer([
    'container.build_hash' => 'HBGT31Q',
    'container.build_id' => '69e72c29',
    'container.build_time' => 1718342730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHBGT31Q');
