<?php

namespace ContainerHBGT31Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PyBpCwFService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.pyBpCwF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pyBpCwF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clienteRepository' => ['privates', 'App\\Repository\\ClienteRepository', 'getClienteRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'estadoRepository' => ['privates', 'App\\Repository\\EstadoRepository', 'getEstadoRepositoryService', true],
            'orderItemRepository' => ['privates', 'App\\Repository\\OrderItemRepository', 'getOrderItemRepositoryService', true],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'pedidoRepository' => ['privates', 'App\\Repository\\PedidoRepository', 'getPedidoRepositoryService', true],
            'stockRepository' => ['privates', 'App\\Repository\\StockRepository', 'getStockRepositoryService', true],
        ], [
            'clienteRepository' => 'App\\Repository\\ClienteRepository',
            'doctrine' => '?',
            'estadoRepository' => 'App\\Repository\\EstadoRepository',
            'orderItemRepository' => 'App\\Repository\\OrderItemRepository',
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'pedidoRepository' => 'App\\Repository\\PedidoRepository',
            'stockRepository' => 'App\\Repository\\StockRepository',
        ]);
    }
}
