<?php

namespace ContainerHBGT31Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Carrito\CartController' shared autowired service.
     *
     * @return \App\Controller\Carrito\CartController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Carrito\\CartController'] = $instance = new \App\Controller\Carrito\CartController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Carrito\\CartController', $container));

        return $instance;
    }
}
