<?php

namespace ContainerHBGT31Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Novedades\OrderItemController' shared autowired service.
     *
     * @return \App\Controller\Novedades\OrderItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Novedades\\OrderItemController'] = $instance = new \App\Controller\Novedades\OrderItemController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Novedades\\OrderItemController', $container));

        return $instance;
    }
}
