<?php

namespace ContainerHBGT31Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderItemTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\OrderItemType' shared autowired service.
     *
     * @return \App\Form\OrderItemType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\OrderItemType'] = new \App\Form\OrderItemType();
    }
}
