<?php

namespace ContainerHBGT31Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedido2TypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Pedido2Type' shared autowired service.
     *
     * @return \App\Form\Pedido2Type
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Pedido2Type'] = new \App\Form\Pedido2Type();
    }
}
