<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVMSiJA7\App_KernelDewDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVMSiJA7/App_KernelDewDebugContainer.php') {
    touch(__DIR__.'/ContainerVMSiJA7.legacy');

    return;
}

if (!\class_exists(App_KernelDewDebugContainer::class, false)) {
    \class_alias(\ContainerVMSiJA7\App_KernelDewDebugContainer::class, App_KernelDewDebugContainer::class, false);
}

return new \ContainerVMSiJA7\App_KernelDewDebugContainer([
    'container.build_hash' => 'VMSiJA7',
    'container.build_id' => 'ad1f5fc2',
    'container.build_time' => 1718468344,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVMSiJA7');
